package codigo;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Álvarez
 */
public class Conectores extends javax.swing.JFrame {
    //
    GestorConexion gc = new GestorConexion();
    PoolConexiones pc = new PoolConexiones();
    /**
     * Creates new form Conectores
     */
    public Conectores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jButtonMostrarTablaClientes = new javax.swing.JButton();
        jButtonMostrarTablaCliente_Producto = new javax.swing.JButton();
        jButtonMostrarTablaProducto = new javax.swing.JButton();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldNum_Contacto = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldDNI_Cliente = new javax.swing.JTextField();
        jTextFieldID_Producto = new javax.swing.JTextField();
        jTextFieldMarca_Producto = new javax.swing.JTextField();
        jTextFieldNombre_Producto = new javax.swing.JTextField();
        jTextFieldFecha_Venta = new javax.swing.JTextField();
        jTextFieldID_producto = new javax.swing.JTextField();
        jTextFieldnombre_producto = new javax.swing.JTextField();
        jTextFieldmarca = new javax.swing.JTextField();
        jTextFieldfecha_venta = new javax.swing.JTextField();
        jButtonAnnadir_Cliente = new javax.swing.JButton();
        jButtonModificar_Cliente = new javax.swing.JButton();
        jButtonEliminar_Cliente = new javax.swing.JButton();
        jButtonAnnadir_Producto = new javax.swing.JButton();
        jButtonModificar_Producto = new javax.swing.JButton();
        jButtonEliminar_Producto = new javax.swing.JButton();
        jButtonAnnadirCliente_Producto = new javax.swing.JButton();
        jButtonModificarCliente_Producto = new javax.swing.JButton();
        jButtonEliminarCliente_Producto = new javax.swing.JButton();
        jButtonBuscar_Cliente = new javax.swing.JButton();
        jTextFieldBuscarCliente = new javax.swing.JTextField();
        jTextFieldBuscarProducto = new javax.swing.JTextField();
        jButtonBuscar_Producto = new javax.swing.JButton();
        jTextFieldBuscarCliente_Producto = new javax.swing.JTextField();
        jButtonBuscar_Cliente_Producto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableResultados);

        jButtonMostrarTablaClientes.setText("Mostrar Tabla Clientes");
        jButtonMostrarTablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMostrarTablaClientesMousePressed(evt);
            }
        });

        jButtonMostrarTablaCliente_Producto.setText("Mostrar Tabla Cliente_Producto");
        jButtonMostrarTablaCliente_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMostrarTablaCliente_ProductoMousePressed(evt);
            }
        });

        jButtonMostrarTablaProducto.setText("Mostrar Tabla Producto");
        jButtonMostrarTablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMostrarTablaProductoMousePressed(evt);
            }
        });

        jTextFieldDNI.setText("DNI");

        jTextFieldNombre.setText("Nombre");

        jTextFieldApellidos.setText("Apellidos");

        jTextFieldCorreo.setText("Correo");

        jTextFieldNum_Contacto.setText("num_Contacto");

        jTextFieldDireccion.setText("Direccion");

        jTextFieldDNI_Cliente.setText("DNI_cliente");

        jTextFieldID_Producto.setText("id_producto");

        jTextFieldMarca_Producto.setText("marca_producto");

        jTextFieldNombre_Producto.setText("nombre_producto");

        jTextFieldFecha_Venta.setText("fecha_venta");

        jTextFieldID_producto.setText("id_producto");

        jTextFieldnombre_producto.setText("nombre_producto");

        jTextFieldmarca.setText("marca");

        jTextFieldfecha_venta.setText("fecha_venta");

        jButtonAnnadir_Cliente.setText("Añadir Cliente");
        jButtonAnnadir_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAnnadir_ClienteMousePressed(evt);
            }
        });

        jButtonModificar_Cliente.setText("Modificar Cliente");
        jButtonModificar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonModificar_ClienteMousePressed(evt);
            }
        });

        jButtonEliminar_Cliente.setText("Eliminar Cliente");
        jButtonEliminar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEliminar_ClienteMousePressed(evt);
            }
        });

        jButtonAnnadir_Producto.setText("Añadir Producto");
        jButtonAnnadir_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAnnadir_ProductoMousePressed(evt);
            }
        });

        jButtonModificar_Producto.setText("Modificar Producto");
        jButtonModificar_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonModificar_ProductoMousePressed(evt);
            }
        });

        jButtonEliminar_Producto.setText("Eliminar Producto");
        jButtonEliminar_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEliminar_ProductoMousePressed(evt);
            }
        });

        jButtonAnnadirCliente_Producto.setText("Añadir Cliente_Producto");
        jButtonAnnadirCliente_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAnnadirCliente_ProductoMousePressed(evt);
            }
        });
        jButtonAnnadirCliente_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirCliente_ProductoActionPerformed(evt);
            }
        });

        jButtonModificarCliente_Producto.setText("Modificar Cliente_Producto");
        jButtonModificarCliente_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonModificarCliente_ProductoMousePressed(evt);
            }
        });

        jButtonEliminarCliente_Producto.setText("Eliminar Cliente_Producto");
        jButtonEliminarCliente_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEliminarCliente_ProductoMousePressed(evt);
            }
        });

        jButtonBuscar_Cliente.setText("Buscar Cliente");
        jButtonBuscar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscar_ClienteMousePressed(evt);
            }
        });
        jButtonBuscar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar_ClienteActionPerformed(evt);
            }
        });

        jButtonBuscar_Producto.setText("Buscar Producto");
        jButtonBuscar_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscar_ProductoMousePressed(evt);
            }
        });

        jButtonBuscar_Cliente_Producto.setText("Buscar Cliente_Producto");
        jButtonBuscar_Cliente_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscar_Cliente_ProductoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNum_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonAnnadir_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jButtonModificar_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDNI_Cliente)
                            .addComponent(jTextFieldID_Producto)
                            .addComponent(jTextFieldMarca_Producto)
                            .addComponent(jTextFieldNombre_Producto)
                            .addComponent(jTextFieldFecha_Venta)
                            .addComponent(jButtonAnnadirCliente_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModificarCliente_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarCliente_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldfecha_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextFieldmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextFieldnombre_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextFieldID_producto)
                            .addComponent(jButtonAnnadir_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModificar_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminar_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMostrarTablaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMostrarTablaCliente_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMostrarTablaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldBuscarCliente_Producto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBuscarProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBuscarCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBuscar_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonBuscar_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonBuscar_Cliente_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDNI_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldID_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldnombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMarca_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldfecha_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNum_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFecha_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAnnadir_Producto)
                                .addComponent(jTextFieldBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBuscar_Cliente))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonMostrarTablaClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarTablaCliente_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarTablaProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAnnadirCliente_Producto))
                    .addComponent(jButtonModificar_Producto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar_Producto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAnnadir_Cliente)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonEliminar_Producto)
                                .addComponent(jButtonModificarCliente_Producto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar_Cliente)
                            .addComponent(jButtonEliminarCliente_Producto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar_Cliente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBuscarCliente_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar_Cliente_Producto)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarTablaClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarTablaClientesMousePressed
        ResultSet rs = gc.Mostrar_TablaClientes();
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        try{
            modelo.addColumn("DNI");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellidos");          //Esto lo que hace es que te pinta las columnas que tiene la tabla de Clientes
            modelo.addColumn("Correo");
            modelo.addColumn("num_Contacto");
            modelo.addColumn("Direccion");
            
            while(rs.next()){
                Object[] obj1 = new Object[6];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));
                obj1[3] = (rs.getString(4));        //Coge los datos que estan insertados en la BBDD y cada dato en la columna que corresponde
                obj1[4] = (rs.getString(5));
                obj1[5] = (rs.getString(6));
                
                modelo.addRow(obj1);
                obj1 = null;
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonMostrarTablaClientesMousePressed

    private void jButtonMostrarTablaCliente_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarTablaCliente_ProductoMousePressed
        ResultSet rs = gc.Mostrar_TablaClientes_Producto();
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        
        try{
            modelo.addColumn("DNI_cliente");
            modelo.addColumn("id_producto");
            modelo.addColumn("marca_producto");     //Esto lo que hace es que te pinta las columnas que tiene la tabla de Cliente_Producto
            modelo.addColumn("nombre_producto");
            modelo.addColumn("fecha_venta");
            
            while(rs.next()){
                Object[] obj1 = new Object[5];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));        //Coge los datos que estan insertados en la BBDD y cada dato en la columna que corresponde
                obj1[3] = (rs.getString(4));
                obj1[4] = (rs.getString(5));
                
                
                modelo.addRow(obj1);
                obj1 = null;
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonMostrarTablaCliente_ProductoMousePressed

    private void jButtonMostrarTablaProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarTablaProductoMousePressed
        ResultSet rs = gc.Mostrar_TablaProductos();
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        
        try{
            modelo.addColumn("id_producto");
            modelo.addColumn("nombre_producto");
            modelo.addColumn("marca");                      //Esto lo que hace es que te pinta las columnas que tiene la tabla de Producto
            modelo.addColumn("fecha_venta");
            
            
            while(rs.next()){
                Object[] obj1 = new Object[4];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));        //Coge los datos que estan insertados en la BBDD y cada dato en la columna que corresponde
                obj1[3] = (rs.getString(4));
              
                
                modelo.addRow(obj1);
                obj1 = null;
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonMostrarTablaProductoMousePressed

    private void jButtonAnnadir_ClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnadir_ClienteMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("INSERT INTO clientes (DNI, Nombre, Apellidos, Correo, num_Contacto, Direccion) VALUES(?,?,?,?,?,?)");
            pst.setString(1, jTextFieldDNI.getText());
            pst.setString(2, jTextFieldNombre.getText());
            pst.setString(3, jTextFieldApellidos.getText());
            pst.setString(4, jTextFieldCorreo.getText());                   //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(5, jTextFieldNum_Contacto.getText());             //la tecla de añadir en este caso para la tabla clientes, te lo inserta en la BBDD
            pst.setString(6, jTextFieldDireccion.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente Guardado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al hacer un INSERT");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente Duplicado");
    }  
    }//GEN-LAST:event_jButtonAnnadir_ClienteMousePressed

    private void jButtonModificar_ClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificar_ClienteMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("Update clientes  SET  Nombre =?, Apellidos =?, Correo =?, num_Contacto =?, Direccion =?  WHERE DNI=?");
            pst.setString(1, jTextFieldNombre.getText());
            pst.setString(2, jTextFieldApellidos.getText());
            pst.setString(3, jTextFieldCorreo.getText());                   //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(4, jTextFieldNum_Contacto.getText());             //el boton Modificar Cliente, te lo modifica en la BBDD de tal forma que se actualiza la tabla con esa modificación.
            pst.setString(5, jTextFieldDireccion.getText());
            pst.setString(6, jTextFieldDNI.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente Modificado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Modificar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente No Modificado");
    }
    }//GEN-LAST:event_jButtonModificar_ClienteMousePressed

    private void jButtonEliminar_ClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminar_ClienteMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("DELETE FROM clientes  WHERE DNI=?");
            pst.setInt(1, Integer.parseInt(jTextFieldDNI.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente Borrado");             //Este método lo que hace es Eliminar la información sobre un cliente en la tabla Clientes en la BBDD.
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Borrar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente No Eliminado");
    }
    }//GEN-LAST:event_jButtonEliminar_ClienteMousePressed

    private void jButtonAnnadir_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnadir_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("INSERT INTO producto (id_producto, nombre_producto, marca, fecha_venta) VALUES(?,?,?,?)");
            pst.setString(1, jTextFieldID_producto.getText());
            pst.setString(2, jTextFieldnombre_producto.getText());
            pst.setString(3, jTextFieldmarca.getText());                    //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(4, jTextFieldfecha_venta.getText());              //la tecla de añadir en este caso para la tabla producto, te lo inserta en la BBDD
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Producto Guardado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al hacer un INSERT");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Producto Duplicado");
    }
    }//GEN-LAST:event_jButtonAnnadir_ProductoMousePressed

    private void jButtonModificar_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificar_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("Update producto  SET  nombre_producto =?, marca =?, fecha_venta =? WHERE id_producto=?");
            pst.setString(1, jTextFieldnombre_producto.getText());
            pst.setString(2, jTextFieldmarca.getText());                    //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(3, jTextFieldfecha_venta.getText());              //el boton Modificar Producto, te lo modifica en la BBDD de tal forma que se actualiza la tabla con esa modificación.
            pst.setString(4, jTextFieldID_producto.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Producto Modificado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Modificar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Producto No Modificado");
    }
    }//GEN-LAST:event_jButtonModificar_ProductoMousePressed

    private void jButtonEliminar_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminar_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("DELETE FROM producto  WHERE id_producto=?");
            pst.setInt(1, Integer.parseInt(jTextFieldID_producto.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Producto Borrado");        //Este método lo que hace es Eliminar la información sobre un Producto en la tabla Producto en la BBDD.
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Borrar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Producto No Eliminado");
    }
    }//GEN-LAST:event_jButtonEliminar_ProductoMousePressed

    private void jButtonAnnadirCliente_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirCliente_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnnadirCliente_ProductoActionPerformed

    private void jButtonAnnadirCliente_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnadirCliente_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("INSERT INTO cliente_producto (DNI_cliente, id_producto, marca_producto, nombre_producto, fecha_venta) VALUES(?,?,?,?,?)");
            pst.setString(1, jTextFieldDNI_Cliente.getText());
            pst.setString(2, jTextFieldID_Producto.getText());              //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(3, jTextFieldMarca_Producto.getText());           //la tecla de añadir en este caso para la tabla cliente_producto, te lo inserta en la BBDD
            pst.setString(4, jTextFieldNombre_Producto.getText());
            pst.setString(5, jTextFieldFecha_Venta.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente_Producto Guardado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al hacer un INSERT");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente_Producto Duplicado");
    }
    }//GEN-LAST:event_jButtonAnnadirCliente_ProductoMousePressed

    private void jButtonModificarCliente_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarCliente_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("Update cliente_producto  SET  nombre_producto =?, marca_producto =?, fecha_venta=?  WHERE id_producto =? AND DNI_cliente =?");
            pst.setString(1, jTextFieldNombre_Producto.getText());
            pst.setString(2, jTextFieldMarca_Producto.getText());
            pst.setString(3, jTextFieldFecha_Venta.getText());              //Este método lo que hace es que te coge los datos de cada jTextField, y que cuando pulsas
            pst.setString(4, jTextFieldID_Producto.getText());              //el boton Modificar Cliente_Producto, te lo modifica en la BBDD de tal forma que se actualiza la tabla con esa modificación.
            pst.setString(5, jTextFieldDNI_Cliente.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente_Producto Modificado");
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Modificar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente_Producto No Modificado");
    }
    }//GEN-LAST:event_jButtonModificarCliente_ProductoMousePressed

    private void jButtonEliminarCliente_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarCliente_ProductoMousePressed
        try{
            gc.conn1.setAutoCommit(false);
            PreparedStatement pst;
            pst = gc.conn1.prepareStatement("DELETE FROM cliente_producto  WHERE id_producto=? AND DNI_cliente=?");
            pst.setInt(1, Integer.parseInt(jTextFieldID_Producto.getText()));
            pst.setInt(2, Integer.parseInt(jTextFieldDNI_Cliente.getText()));
            pst.executeUpdate();                                                    //Este método lo que hace es Eliminar la información sobre un Cliente_Producto en la tabla Cliente_Producto
            JOptionPane.showMessageDialog(null, "Cliente_Producto Borrado");        //en la BBDD.                                                                              
            gc.conn1.commit();
        }
    catch(SQLException ex){
            System.out.println("ERROR: al Borrar");
            try{
                if(gc.conn1!=null)
                    gc.conn1.rollback();
            }catch(SQLException se2){
                se2.printStackTrace();
            }
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cliente_Producto No Eliminado");
    }
    }//GEN-LAST:event_jButtonEliminarCliente_ProductoMousePressed

    private void jButtonBuscar_ClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscar_ClienteMousePressed
        PreparedStatement pst;
        ResultSet rs;
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        try{
            pst = gc.conn1.prepareStatement("SELECT * FROM clientes WHERE DNI=? OR Nombre=?");
            pst.setString(1,jTextFieldBuscarCliente.getText());
            pst.setString(2,jTextFieldBuscarCliente.getText());
            rs = pst.executeQuery();
            modelo.addColumn("DNI");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Correo");                     //Este método te realiza una busqueda en la BBDD en la tabla clientes; y te muestra la información sobre ese cliente en el jTable
            modelo.addColumn("num_Contacto");
            modelo.addColumn("Direccion");
            
            if(rs.next()){
                Object[] obj1 = new Object[6];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));
                obj1[3] = (rs.getString(4));
                obj1[4] = (rs.getString(5));
                obj1[5] = (rs.getString(6));
                
                modelo.addRow(obj1);
                obj1 = null;
            }else{
                JOptionPane.showMessageDialog(null, "No existe este cliente con el DNI");
            }  
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscar_ClienteMousePressed

    private void jButtonBuscar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscar_ClienteActionPerformed

    private void jButtonBuscar_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscar_ProductoMousePressed
        PreparedStatement pst;
        ResultSet rs;
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        try{
            pst = gc.conn1.prepareStatement("SELECT * FROM producto WHERE id_producto=? OR nombre_producto=?");
            pst.setString(1,jTextFieldBuscarProducto.getText());
            pst.setString(2,jTextFieldBuscarProducto.getText());
            rs = pst.executeQuery();
            modelo.addColumn("id_producto");
            modelo.addColumn("nombre_producto");
            modelo.addColumn("marca");                                  //Este método te realiza una busqueda en la BBDD en la tabla producto; y te muestra la información sobre ese producto en el jTable
            modelo.addColumn("fecha_venta");
            
            
            if(rs.next()){
                Object[] obj1 = new Object[4];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));
                obj1[3] = (rs.getString(4));
              
                
                modelo.addRow(obj1);
                obj1 = null;
            
            }else{
                JOptionPane.showMessageDialog(null, "No existe este producto con el ID");
            }  
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscar_ProductoMousePressed

    private void jButtonBuscar_Cliente_ProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscar_Cliente_ProductoMousePressed
        PreparedStatement pst;
        ResultSet rs;
        DefaultTableModel modelo = new DefaultTableModel();
        jTableResultados.setModel(modelo);
        try{
            pst = gc.conn1.prepareStatement("SELECT * FROM cliente_producto WHERE id_producto=? OR DNI_cliente=?");
            pst.setString(1,jTextFieldBuscarCliente_Producto.getText());
            pst.setString(2,jTextFieldBuscarCliente_Producto.getText());
            rs = pst.executeQuery();
            modelo.addColumn("DNI_cliente");
            modelo.addColumn("id_producto");
            modelo.addColumn("marca_producto");                     //Este método te realiza una busqueda en la BBDD en la tabla cliente__producto; y te muestra la información sobre                                                         
            modelo.addColumn("nombre_producto");                    //esa relación entre el cliente y el producto en el jTable
            modelo.addColumn("fecha_venta");
            
            if(rs.next()){
                Object[] obj1 = new Object[5];
                obj1[0] = (rs.getInt(1));
                obj1[1] = (rs.getString(2));
                obj1[2] = (rs.getString(3));
                obj1[3] = (rs.getString(4));
                obj1[4] = (rs.getString(5));
                
                
                modelo.addRow(obj1);
                obj1 = null;
            }else{
                JOptionPane.showMessageDialog(null, "No existe ni este cliente con el DNI ni este producto con ID");
            }  
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscar_Cliente_ProductoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conectores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conectores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnadirCliente_Producto;
    private javax.swing.JButton jButtonAnnadir_Cliente;
    private javax.swing.JButton jButtonAnnadir_Producto;
    private javax.swing.JButton jButtonBuscar_Cliente;
    private javax.swing.JButton jButtonBuscar_Cliente_Producto;
    private javax.swing.JButton jButtonBuscar_Producto;
    private javax.swing.JButton jButtonEliminarCliente_Producto;
    private javax.swing.JButton jButtonEliminar_Cliente;
    private javax.swing.JButton jButtonEliminar_Producto;
    private javax.swing.JButton jButtonModificarCliente_Producto;
    private javax.swing.JButton jButtonModificar_Cliente;
    private javax.swing.JButton jButtonModificar_Producto;
    private javax.swing.JButton jButtonMostrarTablaCliente_Producto;
    private javax.swing.JButton jButtonMostrarTablaClientes;
    private javax.swing.JButton jButtonMostrarTablaProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBuscarCliente;
    private javax.swing.JTextField jTextFieldBuscarCliente_Producto;
    private javax.swing.JTextField jTextFieldBuscarProducto;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNI_Cliente;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFecha_Venta;
    private javax.swing.JTextField jTextFieldID_Producto;
    private javax.swing.JTextField jTextFieldID_producto;
    private javax.swing.JTextField jTextFieldMarca_Producto;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre_Producto;
    private javax.swing.JTextField jTextFieldNum_Contacto;
    private javax.swing.JTextField jTextFieldfecha_venta;
    private javax.swing.JTextField jTextFieldmarca;
    private javax.swing.JTextField jTextFieldnombre_producto;
    // End of variables declaration//GEN-END:variables
}
